const members = (Math.random(1) * 10).toFixed(2);
const repost = (Math.random(1) * 10).toFixed(2);

export const CAROUSEL_CONTENT = [
  {
    src: "https://fastly.picsum.photos/id/16/2500/1667.jpg?hmac=uAkZwYc5phCRNFTrV_prJ_0rP0EdwJaZ4ctje2bY7aE",
    title: "For a More Creative Brain Follow These 5 Steps",
    subtitle: "The Proven Path to Doing Unique and Meaningful Work",
    subreddit: "r/TheSims4",
    icon: "https://fastly.picsum.photos/id/16/2500/1667.jpg?hmac=uAkZwYc5phCRNFTrV_prJ_0rP0EdwJaZ4ctje2bY7aE",
    members: members,
    time: "17 hrs ago",
    repost: repost,
  },
  {
    src: "https://fastly.picsum.photos/id/29/4000/2670.jpg?hmac=rCbRAl24FzrSzwlR5tL-Aqzyu5tX_PA95VJtnUXegGU",
    title: "Creativity Is a Process, Not an Event",
    subtitle: "The Proven Path to Doing Unique and Meaningful Work",
    subreddit: "r/Books",
    icon: "https://fastly.picsum.photos/id/866/536/354.jpg?hmac=tGofDTV7tl2rprappPzKFiZ9vDh5MKj39oa2D--gqhA",
    members: members,
    time: "1 hr ago",
    repost: repost,
  },
  {
    src: "https://fastly.picsum.photos/id/36/4179/2790.jpg?hmac=OCuYYm0PkDCMwxWhrtoSefG5UDir4O0XCcR2x-aSPjs",
    title: "The Ultimate Productivity Hack is Saying No",
    subtitle: "How Experts Figure What to Focus On",
    subreddit: "r/AttackonTitans",
    icon: "https://fastly.picsum.photos/id/173/536/354.jpg?hmac=1R9cMRGVguJT3TphP_Lvx57_YH8MtCIRh3TvZP_VTUo",
    members: members,
    time: "17 mins ago",
    repost: repost,
  },
  {
    src: "https://fastly.picsum.photos/id/238/536/354.jpg?hmac=lTwb8DbxMAh_q5cLhPzEQP7gbKMA4MAythQrpcQSm3U",
    title: "30 One-Sentence Stories From People Who Have Built Better Habits",
    subtitle:
      "The Ultimate Habit Tracker Guide: Why and How to Track Your Habits",
    subreddit: "r/nakedcats",
    icon: "https://fastly.picsum.photos/id/238/536/354.jpg?hmac=lTwb8DbxMAh_q5cLhPzEQP7gbKMA4MAythQrpcQSm3U",
    members: members,
    time: "1 sec ago",
    repost: repost,
  },
  {
    src: "https://fastly.picsum.photos/id/58/1280/853.jpg?hmac=YO3QnOm9TpyM5DqsJjoM4CHg8oIq4cMWLpd9ALoP908",
    title: "For a More Creative Brain Follow These 5 Steps",
    subtitle: "The Proven Path to Doing Unique and Meaningful Work",
    subreddit: "r/crochet",
    icon: "https://fastly.picsum.photos/id/58/1280/853.jpg?hmac=YO3QnOm9TpyM5DqsJjoM4CHg8oIq4cMWLpd9ALoP908",
    members: members,
    time: "17 sec ago",
    repost: repost,
  },
  {
    src: "https://fastly.picsum.photos/id/183/2316/1544.jpg?hmac=908ZBWKqGdL9kio38tCq2ViwMm3DjLUtkjU_6SWNa9k",
    title: "Creativity Is a Process, Not an Event",
    subtitle: "The Proven Path to Doing Unique and Meaningful Work",
    subreddit: "r/gaming",
    icon: "https://fastly.picsum.photos/id/183/2316/1544.jpg?hmac=908ZBWKqGdL9kio38tCq2ViwMm3DjLUtkjU_6SWNa9k",
    members: members,
    time: "2 hrs ago",
    repost: repost,
  },
  {
    src: "https://fastly.picsum.photos/id/36/4179/2790.jpg?hmac=OCuYYm0PkDCMwxWhrtoSefG5UDir4O0XCcR2x-aSPjs",
    title: "The Ultimate Productivity Hack is Saying No",
    subtitle: "How Experts Figure What to Focus On",
    subreddit: "r/Bastille",
    icon: "https://fastly.picsum.photos/id/29/4000/2670.jpg?hmac=rCbRAl24FzrSzwlR5tL-Aqzyu5tX_PA95VJtnUXegGU",
    members: members,
    time: "4 hrs ago",
    repost: repost,
  },
  {
    src: "https://fastly.picsum.photos/id/40/4106/2806.jpg?hmac=MY3ra98ut044LaWPEKwZowgydHZ_rZZUuOHrc3mL5mI",
    title: "30 One-Sentence Stories From People Who Have Built Better Habits",
    subtitle:
      "The Ultimate Habit Tracker Guide: Why and How to Track Your Habits",
    subreddit: "r/OneDirection",
    icon: "https://fastly.picsum.photos/id/29/4000/2670.jpg?hmac=rCbRAl24FzrSzwlR5tL-Aqzyu5tX_PA95VJtnUXegGU",
    members: members,
    time: "17 days ago",
    repost: repost,
  },
];
